/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import DAO.CommandeDAO;
import DAO.ProduitDAO;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class MenuPrincipalFrame extends javax.swing.JFrame {
    public MenuPrincipalFrame() {
        initComponents(); 
        
        this.setExtendedState(MenuPrincipalFrame.MAXIMIZED_BOTH); 
        this.setLayout(new java.awt.BorderLayout());
        
        this.add(jPanel1, java.awt.BorderLayout.NORTH);
        this.add(jPanel2, java.awt.BorderLayout.CENTER);

        tableProduitsAlerte.setOpaque(false);
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jPanel2.setOpaque(false); 

        this.setTitle("Gestion Restaurent-Tableau de Bord");
        this.setLocationRelativeTo(null);
        initialiserMonInterface();
        chargerDonnees();
    }
    
    private void initialiserMonInterface() {
        // Gestion des alertes stock 
        
        itemStockAlerte.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mouseClicked(java.awt.event.MouseEvent e) {
            try {
                ProduitDAO dao = new ProduitDAO();
                var produits = dao.produitsEnAlerte();
                if (produits.isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Aucun produit en alerte de stock.");
                } else {
                    StringBuilder sb = new StringBuilder("📢 PRODUITS EN ALERTE DE STOCK :\n\n");
                    for (var produit : produits) {
                        sb.append("• ").append(produit.getNom()).append(" (").append(produit.getStockActuel()).append(")\n");
                    }
                    JOptionPane.showMessageDialog(null, sb.toString(), "Alerte Stock", JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Erreur: " + ex.getMessage());
            }
        }
   
        
         });
    }
    
    private void chargerDonnees() {
        try {
            ProduitDAO produitDAO = new ProduitDAO();
            var produitsAlerte = produitDAO.produitsEnAlerte();
            
            DefaultTableModel modelAlertes = new DefaultTableModel(
                new Object[]{"Produit", "Catégorie", "Stock", "Seuil"}, 0
            );
            
            for (var produit : produitsAlerte) {
                modelAlertes.addRow(new Object[]{
                    produit.getNom(),
                    produit.getCategorie().getLibelle(),
                    produit.getStockActuel(),
                    produit.getSeuilAlerte()
                });
            }
            tableProduitsAlerte.setModel(modelAlertes); // [cite: 51]
            
        } catch (Exception e) {
            System.err.println("Erreur chargement: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new BackgroundPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProduitsAlerte = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        itemCategories = new javax.swing.JMenuItem();
        itemProduits = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemMouvementsStock = new javax.swing.JMenuItem();
        itemCommandes = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        itemStockAlerte = new javax.swing.JMenuItem();
        itemAbout = new javax.swing.JMenu();
        itemDeconnexion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Restaurent-Tableau de Bord");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUIT EN ALERTE DE STOCK", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        tableProduitsAlerte.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 0, 0)));
        tableProduitsAlerte.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tableProduitsAlerte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Produit", "Catégorie", "Stock", "Seuil"
            }
        ));
        jScrollPane1.setViewportView(tableProduitsAlerte);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Rockwell Extra Bold", 3, 24)); // NOI18N
        jLabel4.setText("                                         RESTAURENT DELICE ELITE ");
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);

        jMenuBar2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu3.setText("Gestion");
        jMenu3.setInheritsPopupMenu(true);

        itemCategories.setText("Catégories");
        itemCategories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCategoriesActionPerformed(evt);
            }
        });
        jMenu3.add(itemCategories);

        itemProduits.setText("Produits");
        itemProduits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProduitsActionPerformed(evt);
            }
        });
        jMenu3.add(itemProduits);
        jMenu3.add(jSeparator1);

        itemMouvementsStock.setText("Mouvements Stock");
        itemMouvementsStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMouvementsStockActionPerformed(evt);
            }
        });
        jMenu3.add(itemMouvementsStock);

        itemCommandes.setText("Commandes");
        itemCommandes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCommandesActionPerformed(evt);
            }
        });
        jMenu3.add(itemCommandes);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Statistique");

        jMenuItem5.setText("Statistiques detaillées");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        itemStockAlerte.setText("Produit en Alerte");
        itemStockAlerte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemStockAlerteActionPerformed(evt);
            }
        });
        jMenu4.add(itemStockAlerte);

        jMenuBar2.add(jMenu4);

        itemAbout.setText("aide");
        jMenuBar2.add(itemAbout);

        itemDeconnexion.setText("Déconnexion");
        jMenuBar2.add(itemDeconnexion);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 929, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCategoriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCategoriesActionPerformed
         CategorieFrame cat = new CategorieFrame();
    
        // L'affiche à l'écran
        cat.setVisible(true);

        // Optionnel : centre la nouvelle fenêtre sur l'écran
        cat.setLocationRelativeTo(null);
    
        // TODO add your handling code here:
    }//GEN-LAST:event_itemCategoriesActionPerformed

    private void itemProduitsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProduitsActionPerformed
         ProduitFrame cat = new ProduitFrame();
    
        // L'affiche à l'écran
        cat.setVisible(true);

        // Optionnel : centre la nouvelle fenêtre sur l'écran
        cat.setLocationRelativeTo(null);
// TODO add your handling code here:
    }//GEN-LAST:event_itemProduitsActionPerformed

    private void itemMouvementsStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMouvementsStockActionPerformed
        StockFrame cat = new StockFrame();
    
        // L'affiche à l'écran
        cat.setVisible(true);

        // Optionnel : centre la nouvelle fenêtre sur l'écran
        cat.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_itemMouvementsStockActionPerformed

    private void itemCommandesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCommandesActionPerformed
         CommandeFrame cat = new CommandeFrame();
    
        // L'affiche à l'écran
        cat.setVisible(true);

        // Optionnel : centre la nouvelle fenêtre sur l'écran
        cat.setLocationRelativeTo(null);
// TODO add your handling code here:
    }//GEN-LAST:event_itemCommandesActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void itemStockAlerteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemStockAlerteActionPerformed
         CategorieFrame cat = new CategorieFrame();
    
        // L'affiche à l'écran
        cat.setVisible(true);

        // Optionnel : centre la nouvelle fenêtre sur l'écran
        cat.setLocationRelativeTo(null);
// TODO add your handling code here:CategorieFrame cat = new CategorieFrame();
   
    }//GEN-LAST:event_itemStockAlerteActionPerformed

                @SuppressWarnings("unchecked")
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
        SwingUtilities.invokeLater(() -> {
            new MenuPrincipalFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itemAbout;
    private javax.swing.JMenuItem itemCategories;
    private javax.swing.JMenuItem itemCommandes;
    private javax.swing.JMenu itemDeconnexion;
    private javax.swing.JMenuItem itemMouvementsStock;
    private javax.swing.JMenuItem itemProduits;
    private javax.swing.JMenuItem itemStockAlerte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable tableProduitsAlerte;
    // End of variables declaration//GEN-END:variables
class BackgroundPanel extends javax.swing.JPanel {
    private java.awt.Image img;
    public BackgroundPanel() {
        img = new javax.swing.ImageIcon(getClass().getResource("/view/image2.png")).getImage();
    }
    @Override
    protected void paintComponent(java.awt.Graphics g) {
        super.paintComponent(g);
        if (img != null) {
            g.drawImage(img, 0, 0, getWidth(), getHeight(), this);
        }
    }
}
}
